#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2021, Qiita development team.
#
# Distributed under the terms of the BSD 3-clause License License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

import click

from qp_spades import plugin


@click.command()
@click.option('--env-script', prompt='Environment script',
              default='conda activate qp_spades')
@click.option('--ca-cert', prompt='Server certificate', default='None')
def config(env_script, ca_cert):
    """Generates the Qiita configuration files"""
    if ca_cert == 'None':
        ca_cert = None
    plugin.generate_config(env_script, 'start_qp_spades', ca_cert)


if __name__ == '__main__':
    config()
